<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bogus" Version="35.6.5"/>
        <PackageReference Include="ClosedXML" Version="0.105.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2"/>
        <PackageReference Include="Syncfusion.Blazor.Spreadsheet" Version="34.2.6" />
        <PackageReference Include="Syncfusion.Blazor.Themes" Version="34.2.6" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Areas\SiteAdam\Components\Layout\" />
        <Folder Include="Areas\SiteAdam\Data\Entity\Pumps\CentrifugalPumpsHistory\"/>
        <Folder Include="Areas\SiteAdam\Views\CentrifugalPumpHistory\"/>
        <Folder Include="Areas\SiteAdam\Views\CentrifugalPump\"/>
        <Folder Include="Areas\SiteAdam\Views\Home\"/>
        <Folder Include="Areas\SiteBram\Controllers\"/>
        <Folder Include="Areas\SiteBram\Models\"/>
        <Folder Include="ExcelFilesPageSave\CentrPumps\" />
        <Folder Include="ExcelFilesPageSave\ContractsCentrPumps\" />
        <Folder Include="Views\Account\"/>
        <Folder Include="Views\Error\"/>
        <Folder Include="Views\Login\"/>
    </ItemGroup>

    <!--
    <ItemGroup>
         <AdditionalFiles Include="Areas\SiteBram\Views\Home\Index.cshtml"/>
        <AdditionalFiles Include="Areas\SiteBram\Views\Shared\_Layout.cshtml"/>
    </ItemGroup>
        -->

    <ItemGroup>
        <_ContentIncludedByDefault Remove="Areas\SiteAdam\Views\Login\Login.cshtml"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="Database\*.sqlite">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Watch Remove="Database\**\*"/>
    </ItemGroup>

</Project>
